Repository boring-km/flutter_todo, pull requests merged in 2021-02, with the labels that each got.

#12 [TD-10-ck] 회원가입 틀 수정
  lib/login.dart
  lib/main.dart
  lib/signup.dart
  lib/todo.dart
Labels: develop

#13 [TD-09-km] 할일 체크하기 구현
  lib/main.dart
  pubspec.yaml
Labels: develop

#14 [TD-10-km] 할일 추가 시 맨 위에 쌓이도록 수정
  lib/main.dart
Labels: bug, develop

#16 [TD-11-km] 할일 수정 기능 추가
  .gitattributes
  .gitignore
  lib/FireBase.dart
  lib/login.dart
  lib/main.dart
Labels: develop

#15 [TD-12-ck] 로그인 및 회원가입 toast
  lib/login.dart
Labels: develop

#17 Revert "[TD-12-ck] 로그인 및 회원가입 toast"
  lib/login.dart
Labels: bug

#18 [TD-12-ck] 로그인 및 회원가입 toast
  lib/login.dart
  pubspec.yaml
Labels: develop

#19 [TD-13-ck] 아이디 중복체크 및 로그아웃 버튼
  lib/login.dart
  lib/main.dart
  pubspec.yaml
Labels: develop
